// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtD87lmw3LfpUxcQTv4xGeG_Wy8kToOiI',
    appId: '1:531673123393:web:9037afa0effeb163c0d4c0',
    messagingSenderId: '531673123393',
    projectId: 'mydiary20050114',
    authDomain: 'mydiary20050114.firebaseapp.com',
    storageBucket: 'mydiary20050114.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8D_ZEQn-PEuHUYpyV8QFv7wH3JsF2TpM',
    appId: '1:531673123393:android:fdc1fe318f22895cc0d4c0',
    messagingSenderId: '531673123393',
    projectId: 'mydiary20050114',
    storageBucket: 'mydiary20050114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqwKwdSjm7U_31bDk4htx1BL5mgGuh-8M',
    appId: '1:531673123393:ios:95c1fd1e84e9bc97c0d4c0',
    messagingSenderId: '531673123393',
    projectId: 'mydiary20050114',
    storageBucket: 'mydiary20050114.firebasestorage.app',
    iosBundleId: 'com.example.myNewDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqwKwdSjm7U_31bDk4htx1BL5mgGuh-8M',
    appId: '1:531673123393:ios:95c1fd1e84e9bc97c0d4c0',
    messagingSenderId: '531673123393',
    projectId: 'mydiary20050114',
    storageBucket: 'mydiary20050114.firebasestorage.app',
    iosBundleId: 'com.example.myNewDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtD87lmw3LfpUxcQTv4xGeG_Wy8kToOiI',
    appId: '1:531673123393:web:ace00bb71647eec6c0d4c0',
    messagingSenderId: '531673123393',
    projectId: 'mydiary20050114',
    authDomain: 'mydiary20050114.firebaseapp.com',
    storageBucket: 'mydiary20050114.firebasestorage.app',
  );
}
